<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnS0s7h\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnS0s7h/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXnS0s7h.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXnS0s7h\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXnS0s7h\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XnS0s7h',
    'container.build_id' => 'c3907caa',
    'container.build_time' => 1573549479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnS0s7h');
